# Generated by Django 4.2.7 on 2024-02-26 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_description', models.CharField(help_text='Enter a valid case description', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('email_address', models.EmailField(help_text='Enter a valid Email Address', max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter a valid first name', max_length=200)),
                ('last_name', models.CharField(help_text='Enter a valid last name', max_length=200)),
                ('gender', models.CharField(help_text='Enter a valid gender', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Enter a valid date of birth', null=True)),
                ('drug_test', models.BooleanField(default=False, help_text='Enter a valid drug test')),
                ('age', models.CharField(help_text='Enter a valid age', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SuspectTestification',
            fields=[
                ('testification_id', models.AutoField(help_text='Enter a valid testification id', primary_key=True, serialize=False)),
                ('answer_1', models.CharField(help_text='Enter a valid crime location', max_length=100)),
                ('answer_2', models.CharField(help_text='Enter a valid crime victim', max_length=100)),
                ('case_description', models.ForeignKey(help_text='Enter a valid Case description', on_delete=django.db.models.deletion.CASCADE, to='peace.case')),
                ('email_address', models.ForeignKey(help_text='Enter a valid suspect id', on_delete=django.db.models.deletion.CASCADE, to='peace.suspect')),
            ],
        ),
    ]
