<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-02-24 15:54
=======
# Generated by Django 4.2.7 on 2024-02-20 20:16
>>>>>>> 7ff2cbcfdbc7181a4fe291243adbdb7c4db75281

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_description', models.CharField(help_text='Enter a valid case description', max_length=200, primary_key=True, serialize=False)),
<<<<<<< HEAD
=======
                ('case_status', models.CharField(help_text='Enter a valid case status', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enforcer',
            fields=[
                ('enforcer_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_description', models.ForeignKey(help_text='Enter a valid Case Description', on_delete=django.db.models.deletion.CASCADE, to='peace.case')),
>>>>>>> 7ff2cbcfdbc7181a4fe291243adbdb7c4db75281
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
<<<<<<< HEAD
                ('email_address', models.EmailField(help_text='Enter a valid Email Address', max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter a valid first name', max_length=200)),
                ('last_name', models.CharField(help_text='Enter a valid last name', max_length=200)),
                ('gender', models.CharField(help_text='Enter a valid gender', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Enter a valid date of birth', null=True)),
                ('drug_test', models.BooleanField(default=False, help_text='Enter a valid drug test')),
                ('age', models.CharField(help_text='Enter a valid age', max_length=200)),
=======
                ('suspect_id', models.AutoField(primary_key=True, serialize=False)),
                ('testification_status', models.BooleanField(default=False, help_text='Enter a valid testification status')),
                ('case_description', models.ForeignKey(help_text='Enter a valid case description', on_delete=django.db.models.deletion.CASCADE, to='peace.case')),
>>>>>>> 7ff2cbcfdbc7181a4fe291243adbdb7c4db75281
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalyser',
            fields=[
<<<<<<< HEAD
                ('analyser_id', models.AutoField(primary_key=True, serialize=False)),
                ('obedient_score', models.FloatField(help_text='Enter a valid emotion score')),
                ('emotion_score', models.FloatField(help_text='Enter a valid emotion score')),
                ('consistency_score', models.FloatField(help_text='Enter a valid consitency score')),
                ('confidence_score', models.FloatField(help_text='Enter a valid confidence score')),
                ('email_address', models.ForeignKey(help_text='Enter a valid suspect id', on_delete=django.db.models.deletion.CASCADE, to='peace.suspect')),
=======
                ('email_address', models.EmailField(help_text='Enter a valid Email Address', max_length=254, primary_key=True, serialize=False)),
                ('user_password', models.CharField(help_text='Enter a valid password', max_length=200)),
                ('first_name', models.CharField(help_text='Enter a valid first name', max_length=200)),
                ('last_name', models.CharField(help_text='Enter a valid last name', max_length=200)),
                ('gender', models.CharField(help_text='Enter a valid gender', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Enter a valid date of birth', null=True)),
                ('drug_test', models.BooleanField(default=False, help_text='Enter a valid drug test')),
                ('age', models.CharField(help_text='Enter a valid age', max_length=200)),
>>>>>>> 7ff2cbcfdbc7181a4fe291243adbdb7c4db75281
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
<<<<<<< HEAD
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.FloatField(help_text='Enter a valid emotion score')),
                ('drug_test', models.BooleanField(default=False, help_text='Enter a valid drug test')),
                ('obedient_score', models.FloatField(help_text='Enter a valid emotion score')),
                ('emotion_score', models.FloatField(help_text='Enter a valid emotion score')),
                ('confidence_score', models.FloatField(help_text='Enter a valid confidence score')),
                ('consistency_score', models.FloatField(help_text='Enter a valid consitency score')),
                ('gender', models.CharField(help_text='Enter a valid gender', max_length=100)),
                ('criminal', models.CharField(help_text='Enter a valid result', max_length=200)),
                ('email_address', models.ForeignKey(help_text='Enter a valid suspect id', on_delete=django.db.models.deletion.CASCADE, to='peace.suspect')),
=======
                ('witness_id', models.AutoField(primary_key=True, serialize=False)),
                ('testification_status', models.BooleanField(default=False, help_text='Enter a valid testification status')),
                ('case_description', models.ForeignKey(help_text='Enter a valid case description', on_delete=django.db.models.deletion.CASCADE, to='peace.case')),
                ('email_address', models.ForeignKey(help_text='Enter a valid email address', on_delete=django.db.models.deletion.CASCADE, to='peace.user')),
>>>>>>> 7ff2cbcfdbc7181a4fe291243adbdb7c4db75281
            ],
        ),
        migrations.CreateModel(
            name='MachineLearningModel',
            fields=[
<<<<<<< HEAD
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.FloatField(help_text='Enter a valid emotion score')),
                ('drug_test', models.BooleanField(default=False, help_text='Enter a valid drug test')),
                ('obidient_score', models.FloatField(help_text='Enter a valid emotion score')),
                ('emotion_score', models.FloatField(help_text='Enter a valid emotion score')),
                ('confidence_score', models.FloatField(help_text='Enter a valid confidence score')),
                ('consistency_score', models.FloatField(help_text='Enter a valid consitency score')),
                ('gender', models.CharField(help_text='Enter a valid gender', max_length=100)),
                ('email_address', models.ForeignKey(help_text='Enter a valid suspect id', on_delete=django.db.models.deletion.CASCADE, to='peace.suspect')),
=======
                ('testification_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_location', models.CharField(help_text='Enter a valid case location', max_length=200)),
                ('case_victim', models.CharField(help_text='Enter a valid crime victim', max_length=200)),
                ('case_incident_date', models.DateField(help_text='Enter a valid case incident date')),
                ('case_incident_time', models.TimeField(help_text='Enter a valid case incident time')),
                ('case_potential_suspect', models.CharField(help_text='Enter a valid case potential suspect', max_length=200)),
                ('case_description', models.ForeignKey(help_text='Enter a valid Case description', on_delete=django.db.models.deletion.CASCADE, to='peace.case')),
                ('witness_id', models.ForeignKey(help_text='Enter a valid witness id', on_delete=django.db.models.deletion.CASCADE, to='peace.witness')),
>>>>>>> 7ff2cbcfdbc7181a4fe291243adbdb7c4db75281
            ],
        ),
        migrations.CreateModel(
            name='SuspectTestification',
            fields=[
                ('testification_id', models.AutoField(help_text='Enter a valid testification id', primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('answer_1', models.CharField(help_text='Enter a valid crime location', max_length=100)),
                ('answer_2', models.CharField(help_text='Enter a valid crime victim', max_length=100)),
                ('case_description', models.ForeignKey(help_text='Enter a valid Case description', on_delete=django.db.models.deletion.CASCADE, to='peace.case')),
                ('email_address', models.ForeignKey(help_text='Enter a valid suspect id', on_delete=django.db.models.deletion.CASCADE, to='peace.suspect')),
=======
                ('crime_location', models.CharField(help_text='Enter a valid crime location', max_length=100)),
                ('crime_victim', models.CharField(help_text='Enter a valid crime victim', max_length=100)),
                ('crime_incident_date', models.DateField(help_text='Enter a valid crime incident date')),
                ('crime_incident_time', models.TimeField(help_text='Enter a valid crime incident time')),
                ('case_description', models.ForeignKey(help_text='Enter a valid Case description', on_delete=django.db.models.deletion.CASCADE, to='peace.case')),
                ('suspect_id', models.ForeignKey(help_text='Enter a valid suspect id', on_delete=django.db.models.deletion.CASCADE, to='peace.suspect')),
            ],
        ),
        migrations.AddField(
            model_name='suspect',
            name='email_address',
            field=models.ForeignKey(help_text='Enter a valid email address', on_delete=django.db.models.deletion.CASCADE, to='peace.user'),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('statement_id', models.AutoField(primary_key=True, serialize=False)),
                ('crime_location', models.CharField(help_text='Enter a valid Crime location', max_length=200)),
                ('crime_victim', models.CharField(help_text='Enter a valid crime victim', max_length=200)),
                ('crime_incident_date', models.DateField(help_text='Enter a valid crime incident date')),
                ('crime_incident_time', models.TimeField(help_text='Enter a valid crime incident time')),
                ('case_description', models.ForeignKey(help_text='Enter a valid Case description', on_delete=django.db.models.deletion.CASCADE, to='peace.case')),
                ('enforcer_id', models.ForeignKey(help_text='Enter a valid Enforcer ID', on_delete=django.db.models.deletion.CASCADE, to='peace.enforcer')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalyser',
            fields=[
                ('analyser_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion_score', models.FloatField(help_text='Enter a valid emotion score')),
                ('confidence_score', models.FloatField(help_text='Enter a valid confidence score')),
                ('consistency_score', models.FloatField(help_text='Enter a valid consitency score')),
                ('suspect_id', models.ForeignKey(help_text='Enter a valid suspect id', on_delete=django.db.models.deletion.CASCADE, to='peace.suspect')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('prediction_result', models.CharField(help_text='Enter a valid result', max_length=200)),
                ('suspect_id', models.ForeignKey(help_text='Enter a valid suspect id', on_delete=django.db.models.deletion.CASCADE, to='peace.suspect')),
>>>>>>> 7ff2cbcfdbc7181a4fe291243adbdb7c4db75281
            ],
        ),
        migrations.AddField(
            model_name='enforcer',
            name='email_address',
            field=models.ForeignKey(help_text='Enter a valid Email Address', on_delete=django.db.models.deletion.CASCADE, to='peace.user'),
        ),
    ]
