# Generated by Django 4.2.7 on 2024-02-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinelearningmodel',
            old_name='obidient_score',
            new_name='obedient_score',
        ),
    ]
