# Generated by Django 4.2.7 on 2024-03-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeparmentNumber',
            new_name='DepartmentNumber',
        ),
    ]
