# Generated by Django 4.2.7 on 2024-03-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0002_rename_deparmentnumber_departmentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peace.departmentnumber'),
        ),
    ]
